### ISSUE TITLE
安卓编译报错

### ISSUE THREAD

**Issue by BitrayStudio** [demoshang/siyuan-patch#1]
已经按说明设置了：KEYSTORE和 KEYSTORE_PASSWORD ，但是安卓还是错误，这个是啥问题呢：

https://github.com/huaanxia/siyuan-patch/actions/runs/6535359292/job/17744633166

**Comment by demoshang** [comment]
![image](https://github.com/demoshang/siyuan-patch/assets/26966709/3fe33b8f-5aa0-4eb0-bbb6-bfdd22c1fab2)


Alias 改成 debug 试试

**Comment by BitrayStudio** [comment]
> ![image](https://user-images.githubusercontent.com/26966709/275674510-3fe33b8f-5aa0-4eb0-bbb6-bfdd22c1fab2.png)
> 
> Alias 改成 debug 试试

ok了，谢谢。
