### ISSUE TITLE
桌面端和安卓端启动后无法自动同步

### ISSUE THREAD

**Issue by ThemanRonin** [demoshang/siyuan-patch#3]
存在如下问题，仅测试在安卓端和Windows端，估计其他端也有问题

**就是在启动后，并不会执行一次自动同步，必须手动执行** 

![image](https://github.com/demoshang/siyuan-patch/assets/35099500/2258a0db-9f62-4f83-b0cf-bb97c49b05d4)
![image](https://github.com/demoshang/siyuan-patch/assets/35099500/f7a4dcda-bef5-4796-ab13-02e0c9b973dd)

**Comment by demoshang** [comment]
已修复
重新下载 [3.0.17](https://github.com/demoshang/siyuan-patch/releases/tag/v3.0.17) 版本
第一次启动不会自动同步,  第二次之后会自动同步

原因是之前没有把配置文件写入到 `~/SiYuan/conf/conf.json`, 启动的时候不能获取到用户信息, 所以无法同步
