### ISSUE TITLE
Android 和 iOS 版本，Actions 编译失败

### ISSUE THREAD

**Issue by neatgz** [demoshang/siyuan-patch#4]
1、Android 和 iOS 版本，Actions 编译失败
https://github.com/demoshang/siyuan-patch/actions/runs/10683121119

2、咨询大佬一个问题，用户名，想把下划线 _ ，更改为其他自定义名称。需要更改 patch 文件里的两处位置吗？谢谢大佬。

![PixPin_2024-09-05_10-44-57](https://github.com/user-attachments/assets/d2562f48-b5d1-4b39-9b68-892b6b3527dc)

**Comment by demoshang** [comment]
编译失效我周末看看, 急用先用老版本吧


下划线改第一个地方（UserName后面应该就可以了）

**Comment by demoshang** [comment]
IOS / Android 编译失效已临时修复 (升级go版本)
