### ISSUE TITLE
老大求教如何编译IOS版本的！

### ISSUE THREAD

**Issue by dahuzi-gege** [demoshang/siyuan-patch#5]
1.老大现在巨魔支持到了17.0了。
2.求老大能不能单独教教IOS的编译。我特意安装了黑苹果然后编译了出来打开竟然发现是空白的。

**Comment by demoshang** [comment]
可以看 `workflows` 文件   

https://github.com/demoshang/siyuan-patch/blob/main/.github/workflows/release-ios.yml#L94

另外, 需要 前端界面和 `Kernel` 都需要, 同样看上面的 `workflow` 文件

**Comment by dahuzi-gege** [comment]
> 可以看 文件`workflows`
> 
> https://github.com/demoshang/siyuan-patch/blob/main/.github/workflows/release-ios.yml#L94
> 
> 另外, 需要 前端界面和 都需要, 同样看上面的 文件`Kernel``workflow`

老大小白的痛苦，不会整哈哈

**Comment by dahuzi-gege** [comment]
[
![D81B0EEB-318C-4C82-A357-716064B73978](https://github.com/user-attachments/assets/58fca47d-cd32-412f-a853-a060eb6a3f69)
老大，这个永远过不去！求教教

**Comment by dahuzi-gege** [comment]
>
