### ISSUE TITLE
不能搜索PDF附件中的内容

### ISSUE THREAD

**Issue by 99999-lee** [demoshang/siyuan-patch#6]
在笔记中尝试添加了几个附件
txt html docx 类型的附件可以搜索
但是PDF类型的搜索不了
希望可以得到支持

**Comment by neatgz** [comment]
> 在笔记中尝试添加了几个附件 txt html docx 类型的附件可以搜索 但是PDF类型的搜索不了 希望可以得到支持

1. 文本型pdf，应该可以搜索。

> #注意#：
> 
> * 不支持大于 4MB 的文本文件
> * 不支持大于 1024 页的 PDF
> * 默认不支持大于 128MB 的 PDF，可通过环境变量 `SIYUAN_PDF_ASSET_CONTENT_INDEX_MAX_SIZE` 设置，值的单位是字节，比如：`SIYUAN_PDF_ASSET_CONTENT_INDEX_MAX_SIZE=256000000` 将上限调整为 256MB
> * Android/iOS 端不支持 PDF 资源文件内容搜索

2. 图片型pdf（扫描版pdf），需要自行配置ocr，才可以搜索内容。

> #图片 OCR 提取文本#
> 
> 该特性仅在桌面端支持，并且需要先手动安装 *Tesseract OCR* 程序。
